#!/usr/bin/bash

path=/home/kristian/LPIC1/script

echo "===================================";

cat $path/script.sh; 
echo "-----------------------------------";
 
cat $path/script2.sh; 
echo "-----------------------------------";
 
cat $path/create-directory-script.sh
echo "===================================";

